version: '3.7'

name: 'phish-tools-compose-prod'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./packages/server/.env.database
    volumes:
      - ./phish-tools-postgres:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5657:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U phishtools']
      interval: 10s
      timeout: 5s
    restart: unless-stopped

  server:
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file:
      - ./packages/server/.env.prod
    environment:
      - ENVIRONMENT=prod
