version: '3.7'

name: 'phish-tools-compose'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'phishtools'
    volumes:
      - phish-tools-postgres:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U phishtools']
      interval: 10s
      timeout: 5s
    restart: unless-stopped

volumes:
  phish-tools-postgres:
    name: phish-tools-postgres
