version: '3.7'

name: 'phish-tools-compose-prod'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env.database
    volumes:
      - ./phish-tools-postgres:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:6869:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U phishtools']
      interval: 10s
      timeout: 5s
    restart: unless-stopped
